/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i polkitagent.h -a :polkitagent.cpp ../interfaces/org.lipstick.polkitAuthAgent.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "polkitagent.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class PolkitAuthAgentAdaptor
 */

PolkitAuthAgentAdaptor::PolkitAuthAgentAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

PolkitAuthAgentAdaptor::~PolkitAuthAgentAdaptor()
{
    // destructor
}

void PolkitAuthAgentAdaptor::accepted()
{
    // handle method call org.lipstick.polkitAuthAgent.accepted
    QMetaObject::invokeMethod(parent(), "accepted");
}

void PolkitAuthAgentAdaptor::cancelAuthentication()
{
    // handle method call org.lipstick.polkitAuthAgent.cancelAuthentication
    QMetaObject::invokeMethod(parent(), "cancelAuthentication");
}

void PolkitAuthAgentAdaptor::finish()
{
    // handle method call org.lipstick.polkitAuthAgent.finish
    QMetaObject::invokeMethod(parent(), "finish");
}

void PolkitAuthAgentAdaptor::initSession()
{
    // handle method call org.lipstick.polkitAuthAgent.initSession
    QMetaObject::invokeMethod(parent(), "initSession");
}

bool PolkitAuthAgentAdaptor::initiateAuthenticationFinish()
{
    // handle method call org.lipstick.polkitAuthAgent.initiateAuthenticationFinish
    bool out0;
    QMetaObject::invokeMethod(parent(), "initiateAuthenticationFinish", Q_RETURN_ARG(bool, out0));
    return out0;
}

void PolkitAuthAgentAdaptor::rejected()
{
    // handle method call org.lipstick.polkitAuthAgent.rejected
    QMetaObject::invokeMethod(parent(), "rejected");
}

void PolkitAuthAgentAdaptor::sessionComplete(bool ok)
{
    // handle method call org.lipstick.polkitAuthAgent.sessionComplete
    QMetaObject::invokeMethod(parent(), "sessionComplete", Q_ARG(bool, ok));
}

void PolkitAuthAgentAdaptor::sessionRequest(const QString &request, bool echo)
{
    // handle method call org.lipstick.polkitAuthAgent.sessionRequest
    QMetaObject::invokeMethod(parent(), "sessionRequest", Q_ARG(QString, request), Q_ARG(bool, echo));
}

